[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_lottery = "7FzPbWJ1eMVTT8YhhzvgJ1H8Yo2AZ76L7xn7ddGA5uyz"

[registry]
url = "https://api.apr.dev"

# solana config set --url localhost(mainnet-beta, testnet, devnet, localhost) 设置网络命令
[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# anchor test --provider.cluster devnet(制定测试并部署网络)
# anchor test --provider.cluster devnet --skip-deploy(跳过部署)
# anchor test --skip-local-validator(跳过本地验证,需先手动启动solana-test-validator程序)
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# npm i -D ts-mocha(package.json如果有不需要在执行)
# npm install --save-dev mocha((package.json如果有不需要在执行))
# 运行命令 anchor run tokenlottery
tokenlottery = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/token-lottery.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "http://localhost:8899"
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"