[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bank_two = "B8o5MhGbbxCxM5ugMZ8WKUpxrDKSUAHktdSQRSCa1S6i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
